# Generated by Django 3.2.4 on 2021-07-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210710_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.teacher'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
